// <auto-generated />
using System;
using Kent.Cli.Rssh.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kent.Cli.Rssh.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220410154527_GroupId on connectiondetails must be nullable")]
    partial class GroupIdonconnectiondetailsmustbenullable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("Kent.Cli.Rssh.Models.ConnectionDetail", b =>
                {
                    b.Property<Guid>("ConnectionDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("ConnectionDetailId");

                    b.HasIndex("GroupId");

                    b.ToTable("ConnectionDetails");
                });

            modelBuilder.Entity("Kent.Cli.Rssh.Models.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Kent.Cli.Rssh.Models.ConnectionDetail", b =>
                {
                    b.HasOne("Kent.Cli.Rssh.Models.Group", null)
                        .WithMany("ConnectionDetails")
                        .HasForeignKey("GroupId");
                });

            modelBuilder.Entity("Kent.Cli.Rssh.Models.Group", b =>
                {
                    b.Navigation("ConnectionDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
