name: .NET Core Desktop

on:
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-22.04  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Test_Project_Path: tests/kentaasvang.Rssh.UnitTests/kentaasvang.Rssh.UnitTests.csproj                 # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Build api-project 
      run: dotnet build src/kentaasvang.Rssh/

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test tests/kentaasvang.Rssh.UnitTests/
